### ISSUE TITLE
seed creating

### ISSUE THREAD

**Issue by phantom1151** [phantamanta44/cloche-plus-plus#1]
this mod is causeing the cloche to create seeds that do not stack. they have all the same info but will not stack at all. im talking basic wheat seeds it very problematic. that is the only problem i have seen but its  a big one so i can not use it in my pack as it causes all kinds of backups in automation systems

if your looking to recreate what im talking about my pack is call Crimson Adventures and you will want to download the 2.6 version of the pack just putt seed in cloche and watch as they do not stack

**Comment by phantamanta44** [comment]
i'll try to look into it soon, but i'm a little inundated by schoolwork at the moment

**Comment by phantamanta44** [comment]
after some investigation, i've determined that this is intended behaviour, and it happens because cloche++ uses the same mechanic to generate new seeds that agricraft uses for single-plant spread. normally, this would create exact copies of the original seed, but you've enabled `Single spread stat increase` in your modpack, which means cloche++ will inherit this behaviour and allow stat increase in generated seeds. i agree that this is kind of annoying though, and i'll add a config option to force exact duplication of seeds.

**Comment by phantamanta44** [comment]
try [this build](https://www.curseforge.com/minecraft/mc-mods/cloche-profit-peripheral/files/2922268)
